apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportmanagement
  labels:
    app: reportmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportmanagement
  template:
    metadata:
      labels:
        app: reportmanagement
    spec:
      containers:
        - name: reportmanagement
          image: team05registry.azurecr.io/reportmanagement:v5
          ports:
            - containerPort: 8080
