apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventmanagement
  labels:
    app: eventmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventmanagement
  template:
    metadata:
      labels:
        app: eventmanagement
    spec:
      containers:
        - name: eventmanagement
          image: team05registry.azurecr.io/eventmanagement:v5
          ports:
            - containerPort: 8080
