apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev", "--hostname-strict=false"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME
              value: "keycloak.20.249.71.251.nip.io"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"


  # keycloak-config-cli:
  #   image: adorsys/keycloak-config-cli
  #   depends_on:
  #     - keycloak
  #   environment:
  #     KEYCLOAK_URL: http://keycloak:8080
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     IMPORT_FILES_LOCATIONS: /config
  #   volumes:
  #     - ./keycloak-config:/config